-- TABLE DDL

CREATE OR REPLACE TABLE EMPLOYEES (
    EMP_ID NUMBER,
    EMP_NAME VARCHAR(100),
    GENDER VARCHAR(20)
);

-- INSER INTO 

INSERT INTO EMPLOYEES (EMP_ID, EMP_NAME, GENDER)
VALUES
    (1, 'Alice', 'Female'),
    (2, 'Diana', 'Female'),
    (3, 'Fiona', 'Female'),
    (4, 'Grace', 'Female'),
    (5, 'Hannah', 'Female'),
    (6, 'Julia', 'Female'),
    (7, 'Bob', 'Male'),
    (8, 'Charlie', 'Male'),
    (9, 'Evan', 'Male'),
    (10, 'Ian', 'Male');

-- METHOD 1 SOLUTION 

-- STEP 1 GENDER & GENDER WISE EMPLOYEE COUNT

WITH GENDER_COUNT AS (
SELECT GENDER,
       COUNT(*) AS GENDER_COUNT      
FROM EMPLOYEES
GROUP BY GENDER
),

-- STEP 2 TOTAL EMPLOYEE COUNT

TOTAL_COUNT AS (
SELECT COUNT (*) AS TOTAL_COUNT
FROM EMPLOYEES
)

-- STEP 3 CROSS JOIN AND CALCULATE THE PERCENTAGE
SELECT G.GENDER,
       G.GENDER_COUNT,
       T.TOTAL_COUNT,
       (G.GENDER_COUNT/T.TOTAL_COUNT) * 100 AS GENDER_PERCENTAGE

FROM GENDER_COUNT      AS G

CROSS JOIN TOTAL_COUNT AS T;


-- METHOD 2 SOLUTION 

-- STEP 1 GENDER & GENDER WISE EMPLOYEE COUNT

WITH GENDER_COUNT AS (
SELECT GENDER,
       COUNT(*) AS GENDER_COUNT      
FROM EMPLOYEES
GROUP BY GENDER
)
--STEP 2 USE SUM AS A WINDOW FUNCTION TO GET THE TOTAL_COUNT
SELECT GENDER,
       GENDER_COUNT,
       SUM(GENDER_COUNT)OVER()            AS TOTAL_COUNT,
       (GENDER_COUNT / TOTAL_COUNT) * 100 AS GENDER_PERCENTAGE

FROM GENDER_COUNT;

-- METHOD 3 SOLUTION

SELECT DISTINCT GENDER,
       COUNT(*)OVER(PARTITION BY GENDER) AS GENDER_COUNT,
       COUNT(*)OVER()                    AS TOTAL_COUNT

FROM EMPLOYEES;

-- FINAL STEP CALCULATE THE GENDER_PERCENTAGE

SELECT DISTINCT GENDER,
       COUNT(*)OVER(PARTITION BY GENDER)  AS GENDER_COUNT,
       COUNT(*)OVER()                     AS TOTAL_COUNT,
       (GENDER_COUNT / TOTAL_COUNT) * 100 AS GENDER_PERCENTAGE

FROM EMPLOYEES;
