-- CREATE TABLE 1
CREATE TABLE TABLE_1 (ID INT);

-- INSERT DATA INTO TABLE 1
INSERT INTO TABLE_1 (ID) VALUES (1),(1),(1),(2),(2),(3),(4),(NULL);


-- CREATE TABLE 2
CREATE TABLE TABLE_2 (ID INT);

-- INSERT DATA INTO TABLE 2
INSERT INTO TABLE_2 (ID) VALUES (1),(1),(2),(3),(3),(4),(5),(NULL);

-- INNER JOIN

SELECT COUNT(*) AS INNER_JOIN_COUNT

FROM TABLE_1 AS T1

INNER JOIN TABLE_2 AS T2 
ON T1.ID = T2.ID;


-- LEFT JOIN

SELECT COUNT(*) AS LEFT_JOIN_COUNT

FROM TABLE_1 AS T1 -- LEFT TABLE

LEFT JOIN TABLE_2 AS T2 
ON T1.ID = T2.ID;

-- RIGHT JOIN

SELECT COUNT(*) AS RIGHT_JOIN_COUNT

FROM TABLE_1 AS T1 -- LEFT TABLE

RIGHT JOIN TABLE_2 AS T2  -- RIGHT TABLE
ON T1.ID = T2.ID;

-- FULL OUTER JOIN

SELECT COUNT(*) AS FULL_OUTER_JOIN_COUNT

FROM TABLE_1 AS T1 -- LEFT TABLE

FULL JOIN TABLE_2 AS T2 -- RIGHT TABLE
ON T1.ID = T2.ID;

-- CROSS JOIN

SELECT COUNT(*) AS CROSS_JOIN_COUNT

FROM TABLE_1 AS T1 -- LEFT TABLE

CROSS JOIN TABLE_2 AS T2; -- RIGHT TABLE
